spring:
  application:
    name: WapFrontDemo
#  thymeleaf:
#    cache: false
#    content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/,classpath:/page/
    add-mappings: true
    cache-period: 3600

server:
  port: 8000

redis:
  sentinel: false
  masterName: resque
  maxIdle: 200
  maxTotal: 2048
  maxWaitMillis: 1000
  hosts: 127.0.0.1:6379
  db: 0
  password:

management:
  security:
    enabled: false

#security:
#  user:
#    name: test
#    password: test

kaptcha:
  properties:
    kaptcha.border: "no"
    kaptcha.textproducer.font.color: "black"
    kaptcha.image.width: "125"
    kaptcha.image.height: "45"
    kaptcha.textproducer.font.size: "38"
    kaptcha.textproducer.char.length: "4"
    kaptcha.textproducer.font.names: 宋体,楷体,微软雅黑
    kaptcha.textproducer.char.space: "2"
    kaptcha.background.clear.from: "white"
    kaptcha.background.clear.to: "white"
    kaptcha.obscurificator.impl: "com.google.code.kaptcha.impl.ShadowGimpy"

